name: Update Jar and Docker Image

on: 
  push:
    paths:
      - productService/**/*

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build JAR 
      run: |
        cd /home/runner/work/phoneStore/phoneStore/productService
        mvn package -Dmaven.test.skip
        cp target/productService-0.0.1-SNAPSHOT.jar /home/runner/work/phoneStore/phoneStore/productService/image

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        cd /home/runner/work/phoneStore/phoneStore/productService/image
        docker build -t your-dockerhub-username/your-image-name:latest .
    #    docker login -u your-dockerhub-username -p ${{ secrets.DOCKERHUB_TOKEN }}
    #    docker push your-dockerhub-username/your-image-name:latest

    - name: Update JAR on GitHub
      run: |
        git config user.name "${{ secrets.GH_USERNAME }}"
        git config user.email "${{ secrets.GH_USERNAME }}"
        git add /home/runner/work/phoneStore/phoneStore/productService/image/productService-0.0.1-SNAPSHOT.jar
        git commit -m "Update JAR"
        git push
