name: Update Jar and Docker Image of database

on: 
  push:
    paths: 
      - database/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        cd /home/runner/work/phoneStore/phoneStore/database
        docker build -t your-dockerhub-username/your-image-name:latest .
    #    docker login -u your-dockerhub-username -p ${{ secrets.DOCKERHUB_TOKEN }}
    #    docker push your-dockerhub-username/your-image-name:latest
