name: Update Jar and Docker Image of database

on: 
  push:
    paths: 
      - database/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        cd /home/runner/work/phoneStore/phoneStore/database
        docker build -t ${{ secrets.DOCKER_USERNAME }}/phonestore_db_image:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/phonestore_db_image:latest
